baseURL: /
languageCode: en-us
defaultContentLanguage: en-us
title: 
theme: hugo-tranquilpeak-theme
disqusShortname: hugo-tranquilpeak-theme
paginate: 7
canonifyurls: yes
permalinks:
  post: /:year/:month/:slug/
taxonomies:
  archive: archives
  category: categories
  tag: tags
author:
  bio: Biostat & Biomath
  gravatarEmail: larry.zhuangzian@gmail.com
  job: UCLA public health
  location: LA
  name: Zian ZHUANG
menu:
  links:
    - identifier: Github
      name: GitHub
      pre: <i class="sidebar-button-icon fa fa-lg fa-github"></i>
      url: https://github.com/Larryzza
      weight: 1
    - identifier: Google scholar
      name: Google scholar
      pre: <i class="sidebar-button-icon fa fa-lg fa-graduation-cap"></i>
      url: https://scholar.google.com/citations?user=7U69CCYAAAAJ&hl=en&oi=ao
      weight: 2
    - identifier: instagram
      name: instagram
      pre: <i class="sidebar-button-icon fa fa-lg fa-instagram"></i>
      url: https://www.instagram.com/larry_zza/
      weight: 3
    - identifier: twitter
      name: twitter
      pre: <i class="sidebar-button-icon fa fa-lg fa-twitter"></i>
      url: https://twitter.com/ZhuangZian
      weight: 4
      
  main:
    - identifier: Home
      name: Home
      pre: <i class="sidebar-button-icon fa fa-lg fa-home"></i>
      url: /
      weight: 1
    - identifier: About me
      name: About
      pre: <i class="sidebar-button-icon fa fa-lg fa-address-card"></i>
      url: /about/
      weight: 2
    - identifier: Selected publications
      name: Publication
      pre: <i class="sidebar-button-icon fa fa-lg fa-leanpub"></i>
      url: /publication/
      weight: 3
    - identifier: Ongoing project
      name: Research
      pre: <i class="sidebar-button-icon fa fa-lg fa-flask"></i>
      url: /research
      weight: 4
    - identifier: Blog
      name: Blog
      pre: <i class="sidebar-button-icon fa fa-lg fa-paper-plane"></i>
      url: /categories
      weight: 5
    - identifier: Contact information
      name: Contact
      pre: <i class="sidebar-button-icon fa fa-lg fa-at"></i>
      url: /contact/
      weight: 6

params:
  math: true
  autoThumbnailImage: yes
  clearReading: yes
  coverImage: images/cover2.jpg
  description: Hugo tranquilpeak theme demo (reversed by Zian)
  hierarchicalCategories: yes
  imageGallery: yes
  sidebarBehavior: 1
  syntaxHighlighter: highlight.js
  thumbnailImage: yes
  thumbnailImagePosition: bottom
