---
title: An interesting joint modeling about COVID-19
author: Zian ZHUANG
date: '2021-03-27'
slug: An interesting joint modeling about COVID-19
categories:
  - Paper appreciation
tags:
  - Bayesian
  - Machine learning
  - SEIR model
header-includes: 
  - \usepackage{bbm}
keywords:
  - tech
comments: no
---
Joint modeling of Bayesian case SEIR (velocity) model with random forest
<!--more-->

[This paper](https://doi.org/10.1101/2020.05.15.20102608) build a SEIR model to forecast the COVID cases, applying the Bayesian method [Markov chain Monte Carlo (MCMC)] to estimated the parameters. Instead of using $R_0$ in the likelihood function, this model defined a parameter `velocity`, which represents capacity to infect (the increment of cumulative cases during a time period), similar as $R_0$. I presume that defining a new parameter here is for the converging purpose. When estimating the parameters in a SEIR model, a proper prior distribution and range would contribute significantly to the convergence of estimates. In addition, uncertainties are also considered in this model. Many papers, especially for SEIR models, did not consider uncertainties in prediction, which may lead decision makers to place undue confidence in their accuracy. 

Another advantage of the model is that it applied a Random Forest model to predict the death of the COVID, based on the simulated _**I**_ population in the SEIR model. Covariates are Age, sex, comorbidity and  the number of newly reported COVID-19 on day $t-1\sim t-14$ in the Random Forest model for location *i* and day *j*. The inverse mortality rate was simulated as a Gaussian distribution with mean 14, standard deviation 1. The benefit of using random forests here is that random forests are insensitive to multicollinearity (it is obvious that cases reported on day $t-1\sim t-14$ are significantly correlated with each other) and can maintain high prediction accuracy. In addition, the model is able to maintain accuracy when a large proportion of the data are missing (it is hard to collect complete demographic data for all patients).

#### Reference
Watson GL, Xiong D, Zhang L, Zoller JA, Shamshoian J, Sundin P, et al. Fusing a Bayesian case velocity model with random forest for predicting COVID-19 in the US. Available at SSRN 3594606. 2020.
